# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from base_drive_chain/ControllerConfig.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControllerConfig(genpy.Message):
  _md5sum = "25f378ae64e2242b15491b758193668c"
  _type = "base_drive_chain/ControllerConfig"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 can_id
int8 drive_direction
int16 home_speed
int32 home_count
"""
  __slots__ = ['can_id','drive_direction','home_speed','home_count']
  _slot_types = ['int16','int8','int16','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       can_id,drive_direction,home_speed,home_count

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControllerConfig, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.can_id is None:
        self.can_id = 0
      if self.drive_direction is None:
        self.drive_direction = 0
      if self.home_speed is None:
        self.home_speed = 0
      if self.home_count is None:
        self.home_count = 0
    else:
      self.can_id = 0
      self.drive_direction = 0
      self.home_speed = 0
      self.home_count = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hbhi().pack(_x.can_id, _x.drive_direction, _x.home_speed, _x.home_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.can_id, _x.drive_direction, _x.home_speed, _x.home_count,) = _get_struct_hbhi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hbhi().pack(_x.can_id, _x.drive_direction, _x.home_speed, _x.home_count))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 9
      (_x.can_id, _x.drive_direction, _x.home_speed, _x.home_count,) = _get_struct_hbhi().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hbhi = None
def _get_struct_hbhi():
    global _struct_hbhi
    if _struct_hbhi is None:
        _struct_hbhi = struct.Struct("<hbhi")
    return _struct_hbhi
