# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from base_drive_chain/MotorState.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotorState(genpy.Message):
  _md5sum = "414d541cba772f96c0da7fb1c738c878"
  _type = "base_drive_chain/MotorState"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int16 speed
int32 position
float32 motor_amps
int16 relative_power
"""
  __slots__ = ['speed','position','motor_amps','relative_power']
  _slot_types = ['int16','int32','float32','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       speed,position,motor_amps,relative_power

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotorState, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.speed is None:
        self.speed = 0
      if self.position is None:
        self.position = 0
      if self.motor_amps is None:
        self.motor_amps = 0.
      if self.relative_power is None:
        self.relative_power = 0
    else:
      self.speed = 0
      self.position = 0
      self.motor_amps = 0.
      self.relative_power = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_hifh().pack(_x.speed, _x.position, _x.motor_amps, _x.relative_power))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.speed, _x.position, _x.motor_amps, _x.relative_power,) = _get_struct_hifh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_hifh().pack(_x.speed, _x.position, _x.motor_amps, _x.relative_power))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 12
      (_x.speed, _x.position, _x.motor_amps, _x.relative_power,) = _get_struct_hifh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_hifh = None
def _get_struct_hifh():
    global _struct_hifh
    if _struct_hifh is None:
        _struct_hifh = struct.Struct("<hifh")
    return _struct_hifh
