// Auto-generated. Do not edit!

// (in-package thorvald_2d_nav.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class RampClimbingGoal {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.timeOut = null;
    }
    else {
      if (initObj.hasOwnProperty('timeOut')) {
        this.timeOut = initObj.timeOut
      }
      else {
        this.timeOut = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type RampClimbingGoal
    // Serialize message field [timeOut]
    bufferOffset = _serializer.int64(obj.timeOut, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type RampClimbingGoal
    let len;
    let data = new RampClimbingGoal(null);
    // Deserialize message field [timeOut]
    data.timeOut = _deserializer.int64(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 8;
  }

  static datatype() {
    // Returns string type for a message object
    return 'thorvald_2d_nav/RampClimbingGoal';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '23ef38af95c519c40b2c7d883c44616f';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    int64 timeOut 
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new RampClimbingGoal(null);
    if (msg.timeOut !== undefined) {
      resolved.timeOut = msg.timeOut;
    }
    else {
      resolved.timeOut = 0
    }

    return resolved;
    }
};

module.exports = RampClimbingGoal;
