TrajectoryPlannerROS:
  max_vel_x: 0.12
  min_vel_x: 0.0
  max_vel_y: 0.0
  min_vel_y: 0.0
  max_vel_theta: 0.12
  min_in_place_vel_theta: 0.1

  acc_lim_theta: 0.5
  acc_lim_x: 0.5
  acc_lim_y: 0

  xy_goal_tolerance: 0.5
  yaw_goal_tolerance: 0.5

  forward_point_distance: 0.1
  dwa: true
  holonomic_robot: false
