obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.825, 0.44], [0.825, -0.44], [-0.825, -0.44], [-0.825, 0.44]]
#robot_radius: ir_of_robot
inflation_radius: 0.55

observation_sources: laser_scan_sensor point_cloud2_sensor

laser_scan_sensor: {sensor_frame: velodyne,  data_type: LaserScan, topic: scan, marking: true, clearing: true}

point_cloud2_sensor: {sensor_frame: velodyne, data_type: PointCloud2, topic: velodyne_points, marking: true, clearing: true}
