// Generated by gencpp from file base_drive_chain/ControllerState.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERSTATE_H
#define BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_drive_chain
{
template <class ContainerAllocator>
struct ControllerState_
{
  typedef ControllerState_<ContainerAllocator> Type;

  ControllerState_()
    : controller_mode(0)
    , battery_volts(0.0)
    , battery_amps(0.0)
    , max_temp(0)
    , status_flags()  {
    }
  ControllerState_(const ContainerAllocator& _alloc)
    : controller_mode(0)
    , battery_volts(0.0)
    , battery_amps(0.0)
    , max_temp(0)
    , status_flags(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _controller_mode_type;
  _controller_mode_type controller_mode;

   typedef float _battery_volts_type;
  _battery_volts_type battery_volts;

   typedef float _battery_amps_type;
  _battery_amps_type battery_amps;

   typedef int16_t _max_temp_type;
  _max_temp_type max_temp;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _status_flags_type;
  _status_flags_type status_flags;




  typedef boost::shared_ptr< ::base_drive_chain::ControllerState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_drive_chain::ControllerState_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerState_

typedef ::base_drive_chain::ControllerState_<std::allocator<void> > ControllerState;

typedef boost::shared_ptr< ::base_drive_chain::ControllerState > ControllerStatePtr;
typedef boost::shared_ptr< ::base_drive_chain::ControllerState const> ControllerStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_drive_chain::ControllerState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_drive_chain::ControllerState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'base_drive_chain': ['/home/vigneshnuc/catkin_ws/src/Thorvald/base_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_drive_chain::ControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cc274a1867f3f7db3f1191e8caf70dc";
  }

  static const char* value(const ::base_drive_chain::ControllerState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cc274a1867f3f7dULL;
  static const uint64_t static_value2 = 0xb3f1191e8caf70dcULL;
};

template<class ContainerAllocator>
struct DataType< ::base_drive_chain::ControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_drive_chain/ControllerState";
  }

  static const char* value(const ::base_drive_chain::ControllerState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_drive_chain::ControllerState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 controller_mode\n\
float32 battery_volts\n\
float32 battery_amps\n\
int16 max_temp\n\
bool[] status_flags\n\
";
  }

  static const char* value(const ::base_drive_chain::ControllerState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_drive_chain::ControllerState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller_mode);
      stream.next(m.battery_volts);
      stream.next(m.battery_amps);
      stream.next(m.max_temp);
      stream.next(m.status_flags);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_drive_chain::ControllerState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_drive_chain::ControllerState_<ContainerAllocator>& v)
  {
    s << indent << "controller_mode: ";
    Printer<int8_t>::stream(s, indent + "  ", v.controller_mode);
    s << indent << "battery_volts: ";
    Printer<float>::stream(s, indent + "  ", v.battery_volts);
    s << indent << "battery_amps: ";
    Printer<float>::stream(s, indent + "  ", v.battery_amps);
    s << indent << "max_temp: ";
    Printer<int16_t>::stream(s, indent + "  ", v.max_temp);
    s << indent << "status_flags[]" << std::endl;
    for (size_t i = 0; i < v.status_flags.size(); ++i)
    {
      s << indent << "  status_flags[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.status_flags[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERSTATE_H
