// Generated by gencpp from file base_drive_chain/ControllerArray.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERARRAY_H
#define BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <base_drive_chain/ControllerData.h>

namespace base_drive_chain
{
template <class ContainerAllocator>
struct ControllerArray_
{
  typedef ControllerArray_<ContainerAllocator> Type;

  ControllerArray_()
    : header()
    , controller_data()  {
    }
  ControllerArray_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , controller_data(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::base_drive_chain::ControllerData_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::base_drive_chain::ControllerData_<ContainerAllocator> >::other >  _controller_data_type;
  _controller_data_type controller_data;




  typedef boost::shared_ptr< ::base_drive_chain::ControllerArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_drive_chain::ControllerArray_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerArray_

typedef ::base_drive_chain::ControllerArray_<std::allocator<void> > ControllerArray;

typedef boost::shared_ptr< ::base_drive_chain::ControllerArray > ControllerArrayPtr;
typedef boost::shared_ptr< ::base_drive_chain::ControllerArray const> ControllerArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_drive_chain::ControllerArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_drive_chain::ControllerArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'base_drive_chain': ['/home/vigneshnuc/catkin_ws/src/Thorvald/base_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerArray_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bd69d6925463f483a09ba76d83f3c179";
  }

  static const char* value(const ::base_drive_chain::ControllerArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbd69d6925463f483ULL;
  static const uint64_t static_value2 = 0xa09ba76d83f3c179ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_drive_chain/ControllerArray";
  }

  static const char* value(const ::base_drive_chain::ControllerArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
ControllerData[] controller_data\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: base_drive_chain/ControllerData\n\
ControllerConfig controller_config\n\
ControllerState controller_state\n\
MotorState propulsion_state\n\
MotorState steering_state\n\
\n\
\n\
================================================================================\n\
MSG: base_drive_chain/ControllerConfig\n\
int16 can_id\n\
int8 drive_direction\n\
int16 home_speed\n\
int32 home_count\n\
\n\
================================================================================\n\
MSG: base_drive_chain/ControllerState\n\
int8 controller_mode\n\
float32 battery_volts\n\
float32 battery_amps\n\
int16 max_temp\n\
bool[] status_flags\n\
\n\
================================================================================\n\
MSG: base_drive_chain/MotorState\n\
int16 speed\n\
int32 position\n\
float32 motor_amps\n\
int16 relative_power\n\
";
  }

  static const char* value(const ::base_drive_chain::ControllerArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.controller_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_drive_chain::ControllerArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_drive_chain::ControllerArray_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "controller_data[]" << std::endl;
    for (size_t i = 0; i < v.controller_data.size(); ++i)
    {
      s << indent << "  controller_data[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::base_drive_chain::ControllerData_<ContainerAllocator> >::stream(s, indent + "    ", v.controller_data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERARRAY_H
