// Generated by gencpp from file base_drive_chain/ControllerData.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERDATA_H
#define BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <base_drive_chain/ControllerConfig.h>
#include <base_drive_chain/ControllerState.h>
#include <base_drive_chain/MotorState.h>
#include <base_drive_chain/MotorState.h>

namespace base_drive_chain
{
template <class ContainerAllocator>
struct ControllerData_
{
  typedef ControllerData_<ContainerAllocator> Type;

  ControllerData_()
    : controller_config()
    , controller_state()
    , propulsion_state()
    , steering_state()  {
    }
  ControllerData_(const ContainerAllocator& _alloc)
    : controller_config(_alloc)
    , controller_state(_alloc)
    , propulsion_state(_alloc)
    , steering_state(_alloc)  {
  (void)_alloc;
    }



   typedef  ::base_drive_chain::ControllerConfig_<ContainerAllocator>  _controller_config_type;
  _controller_config_type controller_config;

   typedef  ::base_drive_chain::ControllerState_<ContainerAllocator>  _controller_state_type;
  _controller_state_type controller_state;

   typedef  ::base_drive_chain::MotorState_<ContainerAllocator>  _propulsion_state_type;
  _propulsion_state_type propulsion_state;

   typedef  ::base_drive_chain::MotorState_<ContainerAllocator>  _steering_state_type;
  _steering_state_type steering_state;




  typedef boost::shared_ptr< ::base_drive_chain::ControllerData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_drive_chain::ControllerData_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerData_

typedef ::base_drive_chain::ControllerData_<std::allocator<void> > ControllerData;

typedef boost::shared_ptr< ::base_drive_chain::ControllerData > ControllerDataPtr;
typedef boost::shared_ptr< ::base_drive_chain::ControllerData const> ControllerDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_drive_chain::ControllerData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_drive_chain::ControllerData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'base_drive_chain': ['/home/vigneshnuc/catkin_ws/src/Thorvald/base_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_drive_chain::ControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c35784ec8577aa62e884e136ae154dc";
  }

  static const char* value(const ::base_drive_chain::ControllerData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c35784ec8577aa6ULL;
  static const uint64_t static_value2 = 0x2e884e136ae154dcULL;
};

template<class ContainerAllocator>
struct DataType< ::base_drive_chain::ControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_drive_chain/ControllerData";
  }

  static const char* value(const ::base_drive_chain::ControllerData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_drive_chain::ControllerData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ControllerConfig controller_config\n\
ControllerState controller_state\n\
MotorState propulsion_state\n\
MotorState steering_state\n\
\n\
\n\
================================================================================\n\
MSG: base_drive_chain/ControllerConfig\n\
int16 can_id\n\
int8 drive_direction\n\
int16 home_speed\n\
int32 home_count\n\
\n\
================================================================================\n\
MSG: base_drive_chain/ControllerState\n\
int8 controller_mode\n\
float32 battery_volts\n\
float32 battery_amps\n\
int16 max_temp\n\
bool[] status_flags\n\
\n\
================================================================================\n\
MSG: base_drive_chain/MotorState\n\
int16 speed\n\
int32 position\n\
float32 motor_amps\n\
int16 relative_power\n\
";
  }

  static const char* value(const ::base_drive_chain::ControllerData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_drive_chain::ControllerData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller_config);
      stream.next(m.controller_state);
      stream.next(m.propulsion_state);
      stream.next(m.steering_state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_drive_chain::ControllerData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_drive_chain::ControllerData_<ContainerAllocator>& v)
  {
    s << indent << "controller_config: ";
    s << std::endl;
    Printer< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >::stream(s, indent + "  ", v.controller_config);
    s << indent << "controller_state: ";
    s << std::endl;
    Printer< ::base_drive_chain::ControllerState_<ContainerAllocator> >::stream(s, indent + "  ", v.controller_state);
    s << indent << "propulsion_state: ";
    s << std::endl;
    Printer< ::base_drive_chain::MotorState_<ContainerAllocator> >::stream(s, indent + "  ", v.propulsion_state);
    s << indent << "steering_state: ";
    s << std::endl;
    Printer< ::base_drive_chain::MotorState_<ContainerAllocator> >::stream(s, indent + "  ", v.steering_state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERDATA_H
