// Generated by gencpp from file base_drive_chain/ControllerConfig.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERCONFIG_H
#define BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERCONFIG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_drive_chain
{
template <class ContainerAllocator>
struct ControllerConfig_
{
  typedef ControllerConfig_<ContainerAllocator> Type;

  ControllerConfig_()
    : can_id(0)
    , drive_direction(0)
    , home_speed(0)
    , home_count(0)  {
    }
  ControllerConfig_(const ContainerAllocator& _alloc)
    : can_id(0)
    , drive_direction(0)
    , home_speed(0)
    , home_count(0)  {
  (void)_alloc;
    }



   typedef int16_t _can_id_type;
  _can_id_type can_id;

   typedef int8_t _drive_direction_type;
  _drive_direction_type drive_direction;

   typedef int16_t _home_speed_type;
  _home_speed_type home_speed;

   typedef int32_t _home_count_type;
  _home_count_type home_count;




  typedef boost::shared_ptr< ::base_drive_chain::ControllerConfig_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_drive_chain::ControllerConfig_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerConfig_

typedef ::base_drive_chain::ControllerConfig_<std::allocator<void> > ControllerConfig;

typedef boost::shared_ptr< ::base_drive_chain::ControllerConfig > ControllerConfigPtr;
typedef boost::shared_ptr< ::base_drive_chain::ControllerConfig const> ControllerConfigConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_drive_chain::ControllerConfig_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'base_drive_chain': ['/home/vigneshnuc/catkin_ws/src/Thorvald/base_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ControllerConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ControllerConfig_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ControllerConfig_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "25f378ae64e2242b15491b758193668c";
  }

  static const char* value(const ::base_drive_chain::ControllerConfig_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x25f378ae64e2242bULL;
  static const uint64_t static_value2 = 0x15491b758193668cULL;
};

template<class ContainerAllocator>
struct DataType< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_drive_chain/ControllerConfig";
  }

  static const char* value(const ::base_drive_chain::ControllerConfig_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 can_id\n\
int8 drive_direction\n\
int16 home_speed\n\
int32 home_count\n\
";
  }

  static const char* value(const ::base_drive_chain::ControllerConfig_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.can_id);
      stream.next(m.drive_direction);
      stream.next(m.home_speed);
      stream.next(m.home_count);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerConfig_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_drive_chain::ControllerConfig_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_drive_chain::ControllerConfig_<ContainerAllocator>& v)
  {
    s << indent << "can_id: ";
    Printer<int16_t>::stream(s, indent + "  ", v.can_id);
    s << indent << "drive_direction: ";
    Printer<int8_t>::stream(s, indent + "  ", v.drive_direction);
    s << indent << "home_speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.home_speed);
    s << indent << "home_count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.home_count);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_CONTROLLERCONFIG_H
