// Generated by gencpp from file base_drive_chain/MotorState.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_MOTORSTATE_H
#define BASE_DRIVE_CHAIN_MESSAGE_MOTORSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace base_drive_chain
{
template <class ContainerAllocator>
struct MotorState_
{
  typedef MotorState_<ContainerAllocator> Type;

  MotorState_()
    : speed(0)
    , position(0)
    , motor_amps(0.0)
    , relative_power(0)  {
    }
  MotorState_(const ContainerAllocator& _alloc)
    : speed(0)
    , position(0)
    , motor_amps(0.0)
    , relative_power(0)  {
  (void)_alloc;
    }



   typedef int16_t _speed_type;
  _speed_type speed;

   typedef int32_t _position_type;
  _position_type position;

   typedef float _motor_amps_type;
  _motor_amps_type motor_amps;

   typedef int16_t _relative_power_type;
  _relative_power_type relative_power;




  typedef boost::shared_ptr< ::base_drive_chain::MotorState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_drive_chain::MotorState_<ContainerAllocator> const> ConstPtr;

}; // struct MotorState_

typedef ::base_drive_chain::MotorState_<std::allocator<void> > MotorState;

typedef boost::shared_ptr< ::base_drive_chain::MotorState > MotorStatePtr;
typedef boost::shared_ptr< ::base_drive_chain::MotorState const> MotorStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_drive_chain::MotorState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_drive_chain::MotorState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'base_drive_chain': ['/home/vigneshnuc/catkin_ws/src/Thorvald/base_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::MotorState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::MotorState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::MotorState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::MotorState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_drive_chain::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "414d541cba772f96c0da7fb1c738c878";
  }

  static const char* value(const ::base_drive_chain::MotorState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x414d541cba772f96ULL;
  static const uint64_t static_value2 = 0xc0da7fb1c738c878ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_drive_chain::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_drive_chain/MotorState";
  }

  static const char* value(const ::base_drive_chain::MotorState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_drive_chain::MotorState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 speed\n\
int32 position\n\
float32 motor_amps\n\
int16 relative_power\n\
";
  }

  static const char* value(const ::base_drive_chain::MotorState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_drive_chain::MotorState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.speed);
      stream.next(m.position);
      stream.next(m.motor_amps);
      stream.next(m.relative_power);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MotorState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_drive_chain::MotorState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_drive_chain::MotorState_<ContainerAllocator>& v)
  {
    s << indent << "speed: ";
    Printer<int16_t>::stream(s, indent + "  ", v.speed);
    s << indent << "position: ";
    Printer<int32_t>::stream(s, indent + "  ", v.position);
    s << indent << "motor_amps: ";
    Printer<float>::stream(s, indent + "  ", v.motor_amps);
    s << indent << "relative_power: ";
    Printer<int16_t>::stream(s, indent + "  ", v.relative_power);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_MOTORSTATE_H
