// Generated by gencpp from file base_drive_chain/MotorControllerSetup.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_MOTORCONTROLLERSETUP_H
#define BASE_DRIVE_CHAIN_MESSAGE_MOTORCONTROLLERSETUP_H

#include <ros/service_traits.h>


#include <base_drive_chain/MotorControllerSetupRequest.h>
#include <base_drive_chain/MotorControllerSetupResponse.h>


namespace base_drive_chain
{

struct MotorControllerSetup
{

typedef MotorControllerSetupRequest Request;
typedef MotorControllerSetupResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MotorControllerSetup
} // namespace base_drive_chain


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::base_drive_chain::MotorControllerSetup > {
  static const char* value()
  {
    return "24c0c7fdc8d1bb416db60b20cb2324c6";
  }

  static const char* value(const ::base_drive_chain::MotorControllerSetup&) { return value(); }
};

template<>
struct DataType< ::base_drive_chain::MotorControllerSetup > {
  static const char* value()
  {
    return "base_drive_chain/MotorControllerSetup";
  }

  static const char* value(const ::base_drive_chain::MotorControllerSetup&) { return value(); }
};


// service_traits::MD5Sum< ::base_drive_chain::MotorControllerSetupRequest> should match 
// service_traits::MD5Sum< ::base_drive_chain::MotorControllerSetup > 
template<>
struct MD5Sum< ::base_drive_chain::MotorControllerSetupRequest>
{
  static const char* value()
  {
    return MD5Sum< ::base_drive_chain::MotorControllerSetup >::value();
  }
  static const char* value(const ::base_drive_chain::MotorControllerSetupRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_drive_chain::MotorControllerSetupRequest> should match 
// service_traits::DataType< ::base_drive_chain::MotorControllerSetup > 
template<>
struct DataType< ::base_drive_chain::MotorControllerSetupRequest>
{
  static const char* value()
  {
    return DataType< ::base_drive_chain::MotorControllerSetup >::value();
  }
  static const char* value(const ::base_drive_chain::MotorControllerSetupRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::base_drive_chain::MotorControllerSetupResponse> should match 
// service_traits::MD5Sum< ::base_drive_chain::MotorControllerSetup > 
template<>
struct MD5Sum< ::base_drive_chain::MotorControllerSetupResponse>
{
  static const char* value()
  {
    return MD5Sum< ::base_drive_chain::MotorControllerSetup >::value();
  }
  static const char* value(const ::base_drive_chain::MotorControllerSetupResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::base_drive_chain::MotorControllerSetupResponse> should match 
// service_traits::DataType< ::base_drive_chain::MotorControllerSetup > 
template<>
struct DataType< ::base_drive_chain::MotorControllerSetupResponse>
{
  static const char* value()
  {
    return DataType< ::base_drive_chain::MotorControllerSetup >::value();
  }
  static const char* value(const ::base_drive_chain::MotorControllerSetupResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_MOTORCONTROLLERSETUP_H
