// Generated by gencpp from file base_drive_chain/ThorvaldTwist.msg
// DO NOT EDIT!


#ifndef BASE_DRIVE_CHAIN_MESSAGE_THORVALDTWIST_H
#define BASE_DRIVE_CHAIN_MESSAGE_THORVALDTWIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/TwistWithCovarianceStamped.h>

namespace base_drive_chain
{
template <class ContainerAllocator>
struct ThorvaldTwist_
{
  typedef ThorvaldTwist_<ContainerAllocator> Type;

  ThorvaldTwist_()
    : header()
    , drive_mode(0)
    , twist()  {
    }
  ThorvaldTwist_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , drive_mode(0)
    , twist(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int16_t _drive_mode_type;
  _drive_mode_type drive_mode;

   typedef  ::geometry_msgs::TwistWithCovarianceStamped_<ContainerAllocator>  _twist_type;
  _twist_type twist;




  typedef boost::shared_ptr< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> const> ConstPtr;

}; // struct ThorvaldTwist_

typedef ::base_drive_chain::ThorvaldTwist_<std::allocator<void> > ThorvaldTwist;

typedef boost::shared_ptr< ::base_drive_chain::ThorvaldTwist > ThorvaldTwistPtr;
typedef boost::shared_ptr< ::base_drive_chain::ThorvaldTwist const> ThorvaldTwistConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace base_drive_chain

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'base_drive_chain': ['/home/vigneshnuc/catkin_ws/src/Thorvald/base_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e18834f49546c94039f55b092de9d1a2";
  }

  static const char* value(const ::base_drive_chain::ThorvaldTwist_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe18834f49546c940ULL;
  static const uint64_t static_value2 = 0x39f55b092de9d1a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "base_drive_chain/ThorvaldTwist";
  }

  static const char* value(const ::base_drive_chain::ThorvaldTwist_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int16 drive_mode\n\
geometry_msgs/TwistWithCovarianceStamped twist\n\
\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovarianceStamped\n\
# This represents an estimated twist with reference coordinate frame and timestamp.\n\
Header header\n\
TwistWithCovariance twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/TwistWithCovariance\n\
# This expresses velocity in free space with uncertainty.\n\
\n\
Twist twist\n\
\n\
# Row-major representation of the 6x6 covariance matrix\n\
# The orientation parameters use a fixed-axis representation.\n\
# In order, the parameters are:\n\
# (x, y, z, rotation about X axis, rotation about Y axis, rotation about Z axis)\n\
float64[36] covariance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::base_drive_chain::ThorvaldTwist_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.drive_mode);
      stream.next(m.twist);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ThorvaldTwist_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::base_drive_chain::ThorvaldTwist_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::base_drive_chain::ThorvaldTwist_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "drive_mode: ";
    Printer<int16_t>::stream(s, indent + "  ", v.drive_mode);
    s << indent << "twist: ";
    s << std::endl;
    Printer< ::geometry_msgs::TwistWithCovarianceStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.twist);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BASE_DRIVE_CHAIN_MESSAGE_THORVALDTWIST_H
