(cl:defpackage base_drive_chain-srv
  (:use )
  (:export
   "MOTORCONTROLLERSETUP"
   "<MOTORCONTROLLERSETUP-REQUEST>"
   "MOTORCONTROLLERSETUP-REQUEST"
   "<MOTORCONTROLLERSETUP-RESPONSE>"
   "MOTORCONTROLLERSETUP-RESPONSE"
   "ROBOTEQMODE"
   "<ROBOTEQMODE-REQUEST>"
   "ROBOTEQMODE-REQUEST"
   "<ROBOTEQMODE-RESPONSE>"
   "ROBOTEQMODE-RESPONSE"
  ))

