; Auto-generated. Do not edit!


(cl:in-package thorvald_2d_nav-msg)


;//! \htmlinclude RampClimbingResult.msg.html

(cl:defclass <RampClimbingResult> (roslisp-msg-protocol:ros-message)
  ((dummy
    :reader dummy
    :initarg :dummy
    :type cl:integer
    :initform 0))
)

(cl:defclass RampClimbingResult (<RampClimbingResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RampClimbingResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RampClimbingResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name thorvald_2d_nav-msg:<RampClimbingResult> is deprecated: use thorvald_2d_nav-msg:RampClimbingResult instead.")))

(cl:ensure-generic-function 'dummy-val :lambda-list '(m))
(cl:defmethod dummy-val ((m <RampClimbingResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader thorvald_2d_nav-msg:dummy-val is deprecated.  Use thorvald_2d_nav-msg:dummy instead.")
  (dummy m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RampClimbingResult>) ostream)
  "Serializes a message object of type '<RampClimbingResult>"
  (cl:let* ((signed (cl:slot-value msg 'dummy)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RampClimbingResult>) istream)
  "Deserializes a message object of type '<RampClimbingResult>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dummy) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RampClimbingResult>)))
  "Returns string type for a message object of type '<RampClimbingResult>"
  "thorvald_2d_nav/RampClimbingResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RampClimbingResult)))
  "Returns string type for a message object of type 'RampClimbingResult"
  "thorvald_2d_nav/RampClimbingResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RampClimbingResult>)))
  "Returns md5sum for a message object of type '<RampClimbingResult>"
  "3a62b28fdf54afb8d2ce8b90d7336086")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RampClimbingResult)))
  "Returns md5sum for a message object of type 'RampClimbingResult"
  "3a62b28fdf54afb8d2ce8b90d7336086")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RampClimbingResult>)))
  "Returns full string definition for message of type '<RampClimbingResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 dummy ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RampClimbingResult)))
  "Returns full string definition for message of type 'RampClimbingResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 dummy ~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RampClimbingResult>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RampClimbingResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RampClimbingResult
    (cl:cons ':dummy (dummy msg))
))
