; Auto-generated. Do not edit!


(cl:in-package thorvald_2d_nav-msg)


;//! \htmlinclude RampClimbingFeedback.msg.html

(cl:defclass <RampClimbingFeedback> (roslisp-msg-protocol:ros-message)
  ((dummy2
    :reader dummy2
    :initarg :dummy2
    :type cl:integer
    :initform 0))
)

(cl:defclass RampClimbingFeedback (<RampClimbingFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RampClimbingFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RampClimbingFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name thorvald_2d_nav-msg:<RampClimbingFeedback> is deprecated: use thorvald_2d_nav-msg:RampClimbingFeedback instead.")))

(cl:ensure-generic-function 'dummy2-val :lambda-list '(m))
(cl:defmethod dummy2-val ((m <RampClimbingFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader thorvald_2d_nav-msg:dummy2-val is deprecated.  Use thorvald_2d_nav-msg:dummy2 instead.")
  (dummy2 m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RampClimbingFeedback>) ostream)
  "Serializes a message object of type '<RampClimbingFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'dummy2)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RampClimbingFeedback>) istream)
  "Deserializes a message object of type '<RampClimbingFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'dummy2) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RampClimbingFeedback>)))
  "Returns string type for a message object of type '<RampClimbingFeedback>"
  "thorvald_2d_nav/RampClimbingFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RampClimbingFeedback)))
  "Returns string type for a message object of type 'RampClimbingFeedback"
  "thorvald_2d_nav/RampClimbingFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RampClimbingFeedback>)))
  "Returns md5sum for a message object of type '<RampClimbingFeedback>"
  "3243b8b6f6a847459b6c91de09c479a8")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RampClimbingFeedback)))
  "Returns md5sum for a message object of type 'RampClimbingFeedback"
  "3243b8b6f6a847459b6c91de09c479a8")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RampClimbingFeedback>)))
  "Returns full string definition for message of type '<RampClimbingFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 dummy2~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RampClimbingFeedback)))
  "Returns full string definition for message of type 'RampClimbingFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%int64 dummy2~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RampClimbingFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RampClimbingFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RampClimbingFeedback
    (cl:cons ':dummy2 (dummy2 msg))
))
