(cl:defpackage base_drive_chain-msg
  (:use )
  (:export
   "<BASESTATE>"
   "BASESTATE"
   "<CONTROLLERARRAY>"
   "CONTROLLERARRAY"
   "<CONTROLLERCONFIG>"
   "CONTROLLERCONFIG"
   "<CONTROLLERDATA>"
   "CONTROLLERDATA"
   "<CONTROLLERINFO>"
   "CONTROLLERINFO"
   "<CONTROLLERSTATE>"
   "CONTROLLERSTATE"
   "<MOTORSTATE>"
   "MOTORSTATE"
   "<THORVALDTWIST>"
   "THORVALDTWIST"
  ))

